![imagen](./img/ejercicios.png)

In [3]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [89]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [91]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
transp = my_matrix.transpose() 
print(transp)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [20]:
np.flip(transp)

array([[20, 15, 10,  5],
       [19, 14,  9,  4],
       [18, 13,  8,  3],
       [17, 12,  7,  2],
       [16, 11,  6,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [23]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [25]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [49]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:
x == "Loro"

array([ True, False, False,  True, False])

In [ ]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [50]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [31]:
x = np.arange(20)
resheip = x.reshape(2,5,2)
print(x)
print(resheip)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
dieces = np.full((3,3), 10)
print (dieces)
print()
print (dieces.nbytes)

def memoria_b(bits):
    if bits < 1:
        return 0
    return 2 ** (bits - 1) + memoria_b(bits - 1)
print()
print(memoria_b(72))

dieces[1][0] = 1
print()
print(dieces)

[[10 10 10]
 [10 10 10]
 [10 10 10]]

72

4722366482869645213695

[[10 10 10]
 [ 1 10 10]
 [10 10 10]]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [46]:
ejer_11 = np.arange(10,50)
print(ejer_11)
print()
print(np.flip(ejer_11))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [60]:
def anti_ceros(vector):
    tu_array = np.array(vector)
    print()
    sin_ceros = tu_array[np.where(tu_array != 0)]
    return sin_ceros
anti_ceros([1,2,4,0,0,4,0])
print()
anti_ceros([4,2,0,0,2,3,4,0,0,0,4,5,0,0,1])


array([4, 2, 2, 3, 4, 4, 5, 1])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8