![imagen](./img/ejercicios.png)

In [4]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(my_array[::-2]) # Se imprimen desde el final los elementos de dos en dos.

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(my_array[-2:-4:-1]) # Se imprimen desde el anteúltimo elemento (8) hasta el cuarto elemento desde el final no inclusive (7). El - 1 indica que se empieza desde el final.

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [9]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(my_array[2::-1]) # Se imprime desde el segundo elemento hasta el final de la lista en orden inverso.

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [11]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
transp = my_matrix.transpose() # Primer se hace la transpuesta de la matriz
print(transp)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [13]:
np.flip(transp) # Para acabar de invertir la matriz se hace un flip de la transpuesta 

array([[20, 15, 10,  5],
       [19, 14,  9,  4],
       [18, 13,  8,  3],
       [17, 12,  7,  2],
       [16, 11,  6,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[:2,:2]) # Lo que se indica entre corchetes marca el límite de las filas y columnas que se recoge en el print (hasta el segundo elemento no inclusive).

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [16]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(my_matrix[::2,::2]) # Esta anotación indica que tanto en filas como en columnas se cogen los datos de manera intercalada (una sí y una no)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [18]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print(my_matrix[:3,::-1]) # El 3 nos indica que se recoge hasta la tercera fila incluida y el -1 que se va a imprimir la matriz con sus elementos invertidos.

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [20]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:
x == "Loro" # La primera forma de aislar Loro se hace comprobando en qué posiciones están para obtener el filtro booleano.

array([ True, False, False,  True, False])

In [ ]:
x[x == "Loro"] # Con ese filtro se aplica al vector de strings inicial para obtener el array con el filtro aplicado.

array(['Loro', 'Loro'], dtype='<U5')

In [ ]:
x[np.where(x == "Loro")] # Este segundo método aplica el where para que imprima sólo los elementos del array que cumplan la condición.

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [24]:
x = np.arange(20)
resheip = x.reshape(2,5,2)
print(x)
print(resheip)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
dieces = np.full((3,3), 10)
print (dieces)
print()
print (dieces.nbytes) # Con estao se obtiene la memoria que ocupa este array (72 bytes)

dieces[1][0] = 1 # Indexamos el cuarto elemento y lo sustituimos por 1
print()
print(dieces)

[[10 10 10]
 [10 10 10]
 [10 10 10]]

72

[[10 10 10]
 [ 1 10 10]
 [10 10 10]]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
ejer_11 = np.arange(10,50)
print(ejer_11)
print()
print(np.flip(ejer_11)) # Con flip invertimos el array

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [ ]:
def anti_ceros(vector): # Se define la función con un argumento
    tu_array = np.array(vector) # Se convierte la lista incluida en el argumento a un array
    print()
    sin_ceros = tu_array[np.where(tu_array != 0)] # Se pasa el filtro para eliminar los 0
    return sin_ceros # Se devuelve el array sin los ceros
anti_ceros([1,2,0,0,4,0])


array([1, 2, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
nueva_matriz = np.random.randint(40, size = (10,10))
print(nueva_matriz)
print()
print(np.min(nueva_matriz)) # Valor mínimo de la matriz
print()
print(np.max(nueva_matriz)) # Valor máximo de la matriz

[[26 38 11 36 27  9  9  9 18 26]
 [32 39 27 33  7 15 21 39  1  8]
 [31 31  4 31 33  6 19 35 38 33]
 [18 33 39 20 29 11  6 20 25 12]
 [10 18 38 18 38 26  3 37 23  6]
 [ 7  6  8 36 23 37  9 32 18 24]
 [23 24 17 18  3  8 10  0 33 29]
 [36  6 37 22 33 33  3 23 11  4]
 [27 29 18  3 27 14 11 18 14 39]
 [16  2 29 10 30 33 30 11 37 23]]

0

39


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
ejer_14 = np.random.randint(1,20, size = (30))
print(ejer_14)
print()
print(np.mean(ejer_14)) # Con mean se saca la media del vector

[14  9 10 11 14 17  6 19  3 13 10 16  2  3 14 13 18  1  6 12 12  7 16  4
 19  9  5  4 15 10]

10.4


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
nueva_matriz2 = np.random.randint(10, size = (5,5)) # Se crea una matriz 5 x 5 con valores de 0 a 9
print(nueva_matriz2)
print()
matriz_norm = ((nueva_matriz2 - np.mean(nueva_matriz2))/np.std(nueva_matriz2)).round(2) # Con esta fórmula obtenemos los valores normalizados de la matriz redondeados a 2 decimales
print(matriz_norm)


[[4 8 7 2 7]
 [6 5 2 4 6]
 [2 8 7 1 1]
 [3 3 4 6 9]
 [0 9 9 9 9]]

[[-0.43  0.96  0.61 -1.13  0.61]
 [ 0.26 -0.08 -1.13 -0.43  0.26]
 [-1.13  0.96  0.61 -1.48 -1.48]
 [-0.78 -0.78 -0.43  0.26  1.31]
 [-1.82  1.31  1.31  1.31  1.31]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
ejer_16 = np.arange(11)
print(ejer_16)
print()
ejer_16_copia = ejer_16.copy()
mi_filtro1 = ([False,False,False,True,True,True,True,True,True,False,False]) # Se crea el filtro entre los valores 3 y 8
ejer_16_copia[mi_filtro1] = -1 # Se sustituye todos los elementos que pasan el filtro por -1
print(ejer_16_copia)

ejer_16_copia2 = ejer_16.copy()
x1, x2, x3 = np.split(ejer_16_copia2, [3, 9]) # Primero hacemos un split para sacar los valores del 3 al 8
np.concatenate((x1,x3)) # Se concantenan los otros dos trozos del vector para obtener el vector final sin los valores del 3 al 8

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


array([ 0,  1,  2,  9, 10])